# XPS binding energy reference database (eV), approximate values based on NIST
# peaks: [{"label": str, "be": float, "fwhm": float}]
# Elements with empty peaks are displayed in the periodic table but not selectable for fitting.

ELEMENTS = {
    # ── Period 1 ──
    "H":  {"Z": 1,  "name": "Hydrogen",    "row": 1, "col": 1,  "cat": "nonmetal",
           "peaks": [{"label": "1s", "be": 14.0,   "fwhm": 0.8}]},
    "He": {"Z": 2,  "name": "Helium",      "row": 1, "col": 18, "cat": "noble_gas",
           "peaks": []},
    # ── Period 2 ──
    "Li": {"Z": 3,  "name": "Lithium",     "row": 2, "col": 1,  "cat": "alkali",
           "peaks": [{"label": "1s", "be": 54.7,   "fwhm": 1.0}]},
    "Be": {"Z": 4,  "name": "Beryllium",   "row": 2, "col": 2,  "cat": "alkaline",
           "peaks": [{"label": "1s", "be": 111.5,  "fwhm": 1.0}]},
    "B":  {"Z": 5,  "name": "Boron",       "row": 2, "col": 13, "cat": "metalloid",
           "peaks": [{"label": "1s", "be": 188.0,  "fwhm": 1.0}]},
    "C":  {"Z": 6,  "name": "Carbon",      "row": 2, "col": 14, "cat": "nonmetal",
           "peaks": [{"label": "1s", "be": 284.8,  "fwhm": 1.2}]},
    "N":  {"Z": 7,  "name": "Nitrogen",    "row": 2, "col": 15, "cat": "nonmetal",
           "peaks": [{"label": "1s", "be": 398.0,  "fwhm": 1.2}]},
    "O":  {"Z": 8,  "name": "Oxygen",      "row": 2, "col": 16, "cat": "nonmetal",
           "peaks": [{"label": "1s", "be": 530.0,  "fwhm": 1.3}]},
    "F":  {"Z": 9,  "name": "Fluorine",    "row": 2, "col": 17, "cat": "halogen",
           "peaks": [{"label": "1s", "be": 685.0,  "fwhm": 1.0}]},
    "Ne": {"Z": 10, "name": "Neon",        "row": 2, "col": 18, "cat": "noble_gas",
           "peaks": []},
    # ── Period 3 ──
    "Na": {"Z": 11, "name": "Sodium",      "row": 3, "col": 1,  "cat": "alkali",
           "peaks": [{"label": "2s", "be": 63.5,   "fwhm": 1.5},
                     {"label": "2p", "be": 31.0,   "fwhm": 1.0}]},
    "Mg": {"Z": 12, "name": "Magnesium",   "row": 3, "col": 2,  "cat": "alkaline",
           "peaks": [{"label": "2s", "be": 88.7,   "fwhm": 1.5},
                     {"label": "2p", "be": 49.8,   "fwhm": 1.0}]},
    "Al": {"Z": 13, "name": "Aluminum",    "row": 3, "col": 13, "cat": "post_trans",
           "peaks": [{"label": "2s", "be": 117.8,  "fwhm": 1.5},
                     {"label": "2p", "be": 72.9,   "fwhm": 1.0}]},
    "Si": {"Z": 14, "name": "Silicon",     "row": 3, "col": 14, "cat": "metalloid",
           "peaks": [{"label": "2s", "be": 149.7,  "fwhm": 1.5},
                     {"label": "2p", "be": 99.4,   "fwhm": 0.8}]},
    "P":  {"Z": 15, "name": "Phosphorus",  "row": 3, "col": 15, "cat": "nonmetal",
           "peaks": [{"label": "2p", "be": 130.0,  "fwhm": 1.0}]},
    "S":  {"Z": 16, "name": "Sulfur",      "row": 3, "col": 16, "cat": "nonmetal",
           "peaks": [{"label": "2p3/2", "be": 164.0, "fwhm": 1.0},
                     {"label": "2p1/2", "be": 165.2, "fwhm": 1.0}]},
    "Cl": {"Z": 17, "name": "Chlorine",    "row": 3, "col": 17, "cat": "halogen",
           "peaks": [{"label": "2p3/2", "be": 198.5, "fwhm": 1.0}]},
    "Ar": {"Z": 18, "name": "Argon",       "row": 3, "col": 18, "cat": "noble_gas",
           "peaks": []},
    # ── Period 4 ──
    "K":  {"Z": 19, "name": "Potassium",   "row": 4, "col": 1,  "cat": "alkali",
           "peaks": [{"label": "2p3/2", "be": 292.8, "fwhm": 1.0}]},
    "Ca": {"Z": 20, "name": "Calcium",     "row": 4, "col": 2,  "cat": "alkaline",
           "peaks": [{"label": "2p3/2", "be": 346.4, "fwhm": 1.2}]},
    "Sc": {"Z": 21, "name": "Scandium",    "row": 4, "col": 3,  "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 398.7, "fwhm": 1.5}]},
    "Ti": {"Z": 22, "name": "Titanium",    "row": 4, "col": 4,  "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 453.9, "fwhm": 1.5},
                     {"label": "2p1/2", "be": 460.2, "fwhm": 2.0}]},
    "V":  {"Z": 23, "name": "Vanadium",    "row": 4, "col": 5,  "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 512.1, "fwhm": 1.5},
                     {"label": "2p1/2", "be": 519.8, "fwhm": 2.0}]},
    "Cr": {"Z": 24, "name": "Chromium",    "row": 4, "col": 6,  "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 574.3, "fwhm": 2.0},
                     {"label": "2p1/2", "be": 583.7, "fwhm": 2.5}]},
    "Mn": {"Z": 25, "name": "Manganese",   "row": 4, "col": 7,  "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 638.7, "fwhm": 2.0},
                     {"label": "2p1/2", "be": 650.0, "fwhm": 2.5}]},
    "Fe": {"Z": 26, "name": "Iron",        "row": 4, "col": 8,  "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 706.8, "fwhm": 1.5},
                     {"label": "2p1/2", "be": 719.9, "fwhm": 2.0}]},
    "Co": {"Z": 27, "name": "Cobalt",      "row": 4, "col": 9,  "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 778.3, "fwhm": 1.5},
                     {"label": "2p1/2", "be": 793.3, "fwhm": 2.0}]},
    "Ni": {"Z": 28, "name": "Nickel",      "row": 4, "col": 10, "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 852.7, "fwhm": 1.5},
                     {"label": "2p1/2", "be": 870.0, "fwhm": 2.0}]},
    "Cu": {"Z": 29, "name": "Copper",      "row": 4, "col": 11, "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 932.7, "fwhm": 1.5},
                     {"label": "2p1/2", "be": 952.5, "fwhm": 2.0}]},
    "Zn": {"Z": 30, "name": "Zinc",        "row": 4, "col": 12, "cat": "transition",
           "peaks": [{"label": "2p3/2", "be": 1021.8,"fwhm": 1.5},
                     {"label": "2p1/2", "be": 1044.9,"fwhm": 2.0}]},
    "Ga": {"Z": 31, "name": "Gallium",     "row": 4, "col": 13, "cat": "post_trans",
           "peaks": [{"label": "3d5/2", "be": 18.7,  "fwhm": 1.0}]},
    "Ge": {"Z": 32, "name": "Germanium",   "row": 4, "col": 14, "cat": "metalloid",
           "peaks": [{"label": "3d5/2", "be": 29.4,  "fwhm": 1.0}]},
    "As": {"Z": 33, "name": "Arsenic",     "row": 4, "col": 15, "cat": "metalloid",
           "peaks": [{"label": "3d5/2", "be": 41.7,  "fwhm": 1.0}]},
    "Se": {"Z": 34, "name": "Selenium",    "row": 4, "col": 16, "cat": "nonmetal",
           "peaks": [{"label": "3d5/2", "be": 55.5,  "fwhm": 1.0}]},
    "Br": {"Z": 35, "name": "Bromine",     "row": 4, "col": 17, "cat": "halogen",
           "peaks": [{"label": "3d5/2", "be": 70.0,  "fwhm": 1.0}]},
    "Kr": {"Z": 36, "name": "Krypton",     "row": 4, "col": 18, "cat": "noble_gas",
           "peaks": []},
    # ── Period 5 ──
    "Rb": {"Z": 37, "name": "Rubidium",    "row": 5, "col": 1,  "cat": "alkali",
           "peaks": [{"label": "3d5/2", "be": 110.0, "fwhm": 1.0}]},
    "Sr": {"Z": 38, "name": "Strontium",   "row": 5, "col": 2,  "cat": "alkaline",
           "peaks": [{"label": "3d5/2", "be": 133.8, "fwhm": 1.0}]},
    "Y":  {"Z": 39, "name": "Yttrium",     "row": 5, "col": 3,  "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 156.7, "fwhm": 1.0}]},
    "Zr": {"Z": 40, "name": "Zirconium",   "row": 5, "col": 4,  "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 178.8, "fwhm": 1.0}]},
    "Nb": {"Z": 41, "name": "Niobium",     "row": 5, "col": 5,  "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 202.3, "fwhm": 1.0}]},
    "Mo": {"Z": 42, "name": "Molybdenum",  "row": 5, "col": 6,  "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 228.0, "fwhm": 1.0},
                     {"label": "3d3/2", "be": 231.1, "fwhm": 1.2}]},
    "Tc": {"Z": 43, "name": "Technetium",  "row": 5, "col": 7,  "cat": "transition",
           "peaks": []},
    "Ru": {"Z": 44, "name": "Ruthenium",   "row": 5, "col": 8,  "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 280.0, "fwhm": 1.0}]},
    "Rh": {"Z": 45, "name": "Rhodium",     "row": 5, "col": 9,  "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 307.2, "fwhm": 1.0}]},
    "Pd": {"Z": 46, "name": "Palladium",   "row": 5, "col": 10, "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 335.1, "fwhm": 1.0},
                     {"label": "3d3/2", "be": 340.4, "fwhm": 1.2}]},
    "Ag": {"Z": 47, "name": "Silver",      "row": 5, "col": 11, "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 368.3, "fwhm": 1.0},
                     {"label": "3d3/2", "be": 374.3, "fwhm": 1.2}]},
    "Cd": {"Z": 48, "name": "Cadmium",     "row": 5, "col": 12, "cat": "transition",
           "peaks": [{"label": "3d5/2", "be": 405.1, "fwhm": 1.2}]},
    "In": {"Z": 49, "name": "Indium",      "row": 5, "col": 13, "cat": "post_trans",
           "peaks": [{"label": "3d5/2", "be": 444.9, "fwhm": 1.2}]},
    "Sn": {"Z": 50, "name": "Tin",         "row": 5, "col": 14, "cat": "post_trans",
           "peaks": [{"label": "3d5/2", "be": 484.9, "fwhm": 1.2}]},
    "Sb": {"Z": 51, "name": "Antimony",    "row": 5, "col": 15, "cat": "metalloid",
           "peaks": [{"label": "3d5/2", "be": 528.2, "fwhm": 1.2}]},
    "Te": {"Z": 52, "name": "Tellurium",   "row": 5, "col": 16, "cat": "metalloid",
           "peaks": [{"label": "3d5/2", "be": 573.0, "fwhm": 1.2}]},
    "I":  {"Z": 53, "name": "Iodine",      "row": 5, "col": 17, "cat": "halogen",
           "peaks": [{"label": "3d5/2", "be": 619.3, "fwhm": 1.2}]},
    "Xe": {"Z": 54, "name": "Xenon",       "row": 5, "col": 18, "cat": "noble_gas",
           "peaks": []},
    # ── Period 6 ──
    "Cs": {"Z": 55, "name": "Cesium",      "row": 6, "col": 1,  "cat": "alkali",
           "peaks": [{"label": "3d5/2", "be": 726.0, "fwhm": 1.2}]},
    "Ba": {"Z": 56, "name": "Barium",      "row": 6, "col": 2,  "cat": "alkaline",
           "peaks": [{"label": "3d5/2", "be": 780.7, "fwhm": 1.5}]},
    "Hf": {"Z": 72, "name": "Hafnium",     "row": 6, "col": 4,  "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 14.2,  "fwhm": 1.0},
                     {"label": "4f5/2", "be": 16.0,  "fwhm": 1.2}]},
    "Ta": {"Z": 73, "name": "Tantalum",    "row": 6, "col": 5,  "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 21.8,  "fwhm": 1.0},
                     {"label": "4f5/2", "be": 23.7,  "fwhm": 1.2}]},
    "W":  {"Z": 74, "name": "Tungsten",    "row": 6, "col": 6,  "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 31.4,  "fwhm": 1.0},
                     {"label": "4f5/2", "be": 33.5,  "fwhm": 1.2}]},
    "Re": {"Z": 75, "name": "Rhenium",     "row": 6, "col": 7,  "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 40.3,  "fwhm": 1.0}]},
    "Os": {"Z": 76, "name": "Osmium",      "row": 6, "col": 8,  "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 50.9,  "fwhm": 1.0}]},
    "Ir": {"Z": 77, "name": "Iridium",     "row": 6, "col": 9,  "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 60.9,  "fwhm": 1.0}]},
    "Pt": {"Z": 78, "name": "Platinum",    "row": 6, "col": 10, "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 71.2,  "fwhm": 1.0},
                     {"label": "4f5/2", "be": 74.5,  "fwhm": 1.2}]},
    "Au": {"Z": 79, "name": "Gold",        "row": 6, "col": 11, "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 84.0,  "fwhm": 1.0},
                     {"label": "4f5/2", "be": 87.6,  "fwhm": 1.2}]},
    "Hg": {"Z": 80, "name": "Mercury",     "row": 6, "col": 12, "cat": "transition",
           "peaks": [{"label": "4f7/2", "be": 99.9,  "fwhm": 1.0}]},
    "Tl": {"Z": 81, "name": "Thallium",    "row": 6, "col": 13, "cat": "post_trans",
           "peaks": [{"label": "4f7/2", "be": 117.8, "fwhm": 1.2}]},
    "Pb": {"Z": 82, "name": "Lead",        "row": 6, "col": 14, "cat": "post_trans",
           "peaks": [{"label": "4f7/2", "be": 136.9, "fwhm": 1.2}]},
    "Bi": {"Z": 83, "name": "Bismuth",     "row": 6, "col": 15, "cat": "post_trans",
           "peaks": [{"label": "4f7/2", "be": 157.0, "fwhm": 1.2}]},
    # ── Period 7 placeholders ──
    "Fr": {"Z": 87, "name": "Francium",    "row": 7, "col": 1,  "cat": "alkali",     "peaks": []},
    "Ra": {"Z": 88, "name": "Radium",      "row": 7, "col": 2,  "cat": "alkaline",   "peaks": []},
    # ── Lanthanides (row 8) ──
    "La": {"Z": 57, "name": "Lanthanum",   "row": 8, "col": 4,  "cat": "lanthanide",
           "peaks": [{"label": "3d5/2", "be": 835.0, "fwhm": 2.0}]},
    "Ce": {"Z": 58, "name": "Cerium",      "row": 8, "col": 5,  "cat": "lanthanide",
           "peaks": [{"label": "3d5/2", "be": 882.0, "fwhm": 2.0}]},
    "Pr": {"Z": 59, "name": "Praseodymium","row": 8, "col": 6,  "cat": "lanthanide", "peaks": []},
    "Nd": {"Z": 60, "name": "Neodymium",   "row": 8, "col": 7,  "cat": "lanthanide", "peaks": []},
    "Sm": {"Z": 62, "name": "Samarium",    "row": 8, "col": 9,  "cat": "lanthanide", "peaks": []},
    "Eu": {"Z": 63, "name": "Europium",    "row": 8, "col": 10, "cat": "lanthanide",
           "peaks": [{"label": "3d5/2", "be": 1127.0,"fwhm": 2.0}]},
    "Gd": {"Z": 64, "name": "Gadolinium",  "row": 8, "col": 11, "cat": "lanthanide", "peaks": []},
    "Tb": {"Z": 65, "name": "Terbium",     "row": 8, "col": 12, "cat": "lanthanide", "peaks": []},
    "Dy": {"Z": 66, "name": "Dysprosium",  "row": 8, "col": 13, "cat": "lanthanide", "peaks": []},
    "Ho": {"Z": 67, "name": "Holmium",     "row": 8, "col": 14, "cat": "lanthanide", "peaks": []},
    "Er": {"Z": 68, "name": "Erbium",      "row": 8, "col": 15, "cat": "lanthanide", "peaks": []},
    "Tm": {"Z": 69, "name": "Thulium",     "row": 8, "col": 16, "cat": "lanthanide", "peaks": []},
    "Yb": {"Z": 70, "name": "Ytterbium",   "row": 8, "col": 17, "cat": "lanthanide", "peaks": []},
    "Lu": {"Z": 71, "name": "Lutetium",    "row": 8, "col": 18, "cat": "lanthanide", "peaks": []},
}

CATEGORY_COLORS = {
    "alkali":      "#e03131",
    "alkaline":    "#f76707",
    "transition":  "#1971c2",
    "post_trans":  "#0ca678",
    "metalloid":   "#2f9e44",
    "nonmetal":    "#6741d9",
    "halogen":     "#c2255c",
    "noble_gas":   "#555e6e",
    "lanthanide":  "#e67700",
    "actinide":    "#862e9c",
}

CATEGORY_NAMES_ZH = {
    "alkali":      "鹼金屬",
    "alkaline":    "鹼土金屬",
    "transition":  "過渡金屬",
    "post_trans":  "後過渡金屬",
    "metalloid":   "類金屬",
    "nonmetal":    "非金屬",
    "halogen":     "鹵素",
    "noble_gas":   "稀有氣體",
    "lanthanide":  "鑭系元素",
    "actinide":    "錒系元素",
}

# Elements available for peak fitting (have at least one peak entry)
FITTABLE_ELEMENTS = {s: d for s, d in ELEMENTS.items() if d["peaks"]}
